package net.devtech.yajslib.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * any method annotated with this should only have one parameter as the input stream, and must be declared <b>final</b>
 * @see net.devtech.yajslib.io.PersistentInput
 */
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface Reader {
	/**
	 * the version number of the class
	 * @return generated by the AP
	 */
	long value();
}
