package net.devtech.yajslib.persistent;

import net.devtech.yajslib.annotations.Reader;
import net.devtech.yajslib.annotations.Writer;
import net.devtech.yajslib.io.PersistentInputStream;
import net.devtech.yajslib.io.PersistentOutputStream;

/**
 * these are autogenerated by the AP based on {@link Writer} and {@link Reader}
 * @param <T> the type being serialized
 */
public interface Persistent<T> {
	long versionHash();
	void write(Object object, PersistentOutputStream output);
	T read(PersistentInputStream input);
}
